server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pdd_leader?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: LeaderService

mybatis:
  type-aliases-package: pojo
  configuration:
    map-underscore-to-camel-case: true
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #logging:
  #  level:
  #    eud.zhu.user: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/,http://127.0.0.1:10087/eureka/
pattern:
  name: 本地环境local
